import { type Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header/Header";
import "@/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
        className="geistsans_9fc57718-module__E7HqPG__variable geistmono_b9f59162-module__dmiviG__variable"
        suppressHydrationWarning
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
